### ISSUE TITLE
Lab-2 fails with pip error at docker build step "RUN pip install jupyter"

### ISSUE THREAD

**Issue by buzzynz** [awslabs/ecs-deep-learning-workshop#6]
Looks like it's using the inbuilt system pip v1.5.2 and doing a pip --upgrade doesn't touch the system pip.
Eventual workaround was to add steps to the Dockerfile to download and run get-pip.py which upgraded pip to 9.0.1; the error below then disappeared.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'widgetsnbextension ~=2.0.0', 'at', ' ~=2.0.0')

**Comment by lserpietri** [comment]
just add 
`RUN wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py`
before the Juptyer installation

**Comment by lserp** [comment]
Just add this two lines on the Dockerfile before the Jupyter installation 
`RUN wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py`
`RUN pip install setuptools==33.1.1`

**Comment by schmutze** [comment]
Fixed- thanks @buzzynz and @lserpietri !
